//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CadastroLogin.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class GlobalResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal GlobalResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CadastroLogin.Resources.GlobalResource", typeof(GlobalResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cadastrar Curso.
        /// </summary>
        public static string CadastrarCurso {
            get {
                return ResourceManager.GetString("CadastrarCurso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cadastre-se.
        /// </summary>
        public static string Cadastrese {
            get {
                return ResourceManager.GetString("Cadastrese", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confira nossos cursos!.
        /// </summary>
        public static string CarrosselCursos {
            get {
                return ResourceManager.GetString("CarrosselCursos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aqui você encontrar nossas principais categorias em destaque!.
        /// </summary>
        public static string CatDestaque {
            get {
                return ResourceManager.GetString("CatDestaque", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Categorias.
        /// </summary>
        public static string Categorias {
            get {
                return ResourceManager.GetString("Categorias", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entrar.
        /// </summary>
        public static string Entrar {
            get {
                return ResourceManager.GetString("Entrar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Formulário de Cadastro.
        /// </summary>
        public static string FormularioCadastro {
            get {
                return ResourceManager.GetString("FormularioCadastro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Formulário de Acesso.
        /// </summary>
        public static string FormularioLogin {
            get {
                return ResourceManager.GetString("FormularioLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aprenda tudo sobre Front-End!.
        /// </summary>
        public static string Front_End {
            get {
                return ResourceManager.GetString("Front-End", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Todos os cursos relacionados a front-end estão aqui!.
        /// </summary>
        public static string IndexCat1 {
            get {
                return ResourceManager.GetString("IndexCat1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se torne um profssional capacitado a trabalha com Back-End!.
        /// </summary>
        public static string IndexCat2 {
            get {
                return ResourceManager.GetString("IndexCat2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inglês.
        /// </summary>
        public static string Ingles {
            get {
                return ResourceManager.GetString("Ingles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Início.
        /// </summary>
        public static string Inicio {
            get {
                return ResourceManager.GetString("Inicio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Linguagem.
        /// </summary>
        public static string Linguagem {
            get {
                return ResourceManager.GetString("Linguagem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lista de cursos.
        /// </summary>
        public static string ListaCat1 {
            get {
                return ResourceManager.GetString("ListaCat1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lista de Usuários.
        /// </summary>
        public static string ListaUsuarios {
            get {
                return ResourceManager.GetString("ListaUsuarios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Perfil.
        /// </summary>
        public static string Perfil {
            get {
                return ResourceManager.GetString("Perfil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A DevKey surgiu da necessidade de uma plataforma de ensino com qualidade e com preço acessível para todos, nosso objetivo é formar cada vez mais
        ///                        desenvolvedores aptos a entrarem no mercado de trabalho após finalizarem nossos cursos, já que a DevKey vem ganhando cada vez mais espaço dentro do mercado profissional..
        /// </summary>
        public static string Plataforma {
            get {
                return ResourceManager.GetString("Plataforma", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Português.
        /// </summary>
        public static string Portugues {
            get {
                return ResourceManager.GetString("Portugues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Principais.
        /// </summary>
        public static string Principais {
            get {
                return ResourceManager.GetString("Principais", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sair.
        /// </summary>
        public static string Sair {
            get {
                return ResourceManager.GetString("Sair", resourceCulture);
            }
        }

        public static string Usuario
        {
            get
            {
                return ResourceManager.GetString("Usuário", resourceCulture);
            }
        }
    }
}
