//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CadastroLogin.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class GlobalResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal GlobalResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CadastroLogin.Resources.GlobalResource", typeof(GlobalResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bem vindo à DevKey.
        /// </summary>
        public static string BemVindo {
            get {
                return ResourceManager.GetString("BemVindo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cursos on-line totalmente gratuitos para você se tornar um programador de sucesso. A chave para o desenvolvimento se encontra aqui!.
        /// </summary>
        public static string BemVindoDesc {
            get {
                return ResourceManager.GetString("BemVindoDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cadastrar Curso.
        /// </summary>
        public static string CadastrarCurso {
            get {
                return ResourceManager.GetString("CadastrarCurso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cadastre-se.
        /// </summary>
        public static string Cadastrese {
            get {
                return ResourceManager.GetString("Cadastrese", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confira nossos cursos!.
        /// </summary>
        public static string CarrosselCursos {
            get {
                return ResourceManager.GetString("CarrosselCursos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aqui você encontrar nossas principais categorias em destaque!.
        /// </summary>
        public static string CatDestaque {
            get {
                return ResourceManager.GetString("CatDestaque", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aprenda a programar Back-End e entre no mercado de trabalho!.
        /// </summary>
        public static string CategoriaBack {
            get {
                return ResourceManager.GetString("CategoriaBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O Banco de dados é uma ferramente indispensável e utilizada em qualquer aplicação atualmente, seja SQL Server, MySql, entre outras..
        /// </summary>
        public static string CategoriaDB {
            get {
                return ResourceManager.GetString("CategoriaDB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tudo o que você precisa saber para dominar o Front-end!.
        /// </summary>
        public static string CategoriaFront {
            get {
                return ResourceManager.GetString("CategoriaFront", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uma das linguagens de programação mais utilizada de todos os tempos, devido a sua escalabilidade e por ser multiplataforma, saiba mais clicando aqui!.
        /// </summary>
        public static string CategoriaJava {
            get {
                return ResourceManager.GetString("CategoriaJava", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cursos para aprender a utilizar esse sistema operacional extraindo ao máximo de seus recursos..
        /// </summary>
        public static string CategoriaLinux {
            get {
                return ResourceManager.GetString("CategoriaLinux", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aprenda tudo sobre desenvolvimento de aplicações mobile, seja em Java ou Kotlin..
        /// </summary>
        public static string CategoriaMobile {
            get {
                return ResourceManager.GetString("CategoriaMobile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Categorias.
        /// </summary>
        public static string Categorias {
            get {
                return ResourceManager.GetString("Categorias", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Segurança digital se tornou um tema de grande importância que deve ser conhecida por todos que desejam entrar no mercado de T.I.
        /// </summary>
        public static string CategoriaSecurity {
            get {
                return ResourceManager.GetString("CategoriaSecurity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se preocupar com a experiência do usuário ao utilizar seu sistema é muito importante, aprenda mais sobre UX Design acessando essa categoria.
        /// </summary>
        public static string CategoriaUX {
            get {
                return ResourceManager.GetString("CategoriaUX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A Devkey conta com um sistema de categorias de curso para melhor entendimento do usuário, com uma breve descrição
        ///                                    de cada categoria..
        /// </summary>
        public static string CategoryTitle {
            get {
                return ResourceManager.GetString("CategoryTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Certificado ao término do curso..
        /// </summary>
        public static string Certificado {
            get {
                return ResourceManager.GetString("Certificado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chat online para tirar dúvidas;.
        /// </summary>
        public static string Chat {
            get {
                return ResourceManager.GetString("Chat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A DevKey salvou minha vida..
        /// </summary>
        public static string Comentario11 {
            get {
                return ResourceManager.GetString("Comentario11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não tenho tempo nem dinheiro para fazer faculdade. Minha meta é tornar-me um desenvolvedor da web freelancer e, graças à Devkey, estou a um passo disso..
        /// </summary>
        public static string Comentario12 {
            get {
                return ResourceManager.GetString("Comentario12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;A plataforma é incrível. Além das metodologias do curso serem de alcance pois as aulas saõ totalmente gratuitas, para quem está começando ou quem já está avançado em alguma tecnologia, no fórum de dúvidas sempre algum instrutor te responde em um curto espaço de tempo..
        /// </summary>
        public static string Comentario21 {
            get {
                return ResourceManager.GetString("Comentario21", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Na Devkey, seu conhecimento é prioridade.&quot;.
        /// </summary>
        public static string Comentario22 {
            get {
                return ResourceManager.GetString("Comentario22", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se você não sabe a ordem do que deve aprender e praticar para dominar uma tecnologia, a forma como os cursos estão organizados e estruturados na DevKey ajuda muito..
        /// </summary>
        public static string Comentario3 {
            get {
                return ResourceManager.GetString("Comentario3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contato.
        /// </summary>
        public static string Contato {
            get {
                return ResourceManager.GetString("Contato", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entrar.
        /// </summary>
        public static string Entrar {
            get {
                return ResourceManager.GetString("Entrar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Formulário de Cadastro.
        /// </summary>
        public static string FormularioCadastro {
            get {
                return ResourceManager.GetString("FormularioCadastro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Formulário de Acesso.
        /// </summary>
        public static string FormularioLogin {
            get {
                return ResourceManager.GetString("FormularioLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aprenda tudo sobre Front-End!.
        /// </summary>
        public static string FrontEnd {
            get {
                return ResourceManager.GetString("FrontEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Todos os cursos relacionados a front-end estão aqui!.
        /// </summary>
        public static string IndexCat1 {
            get {
                return ResourceManager.GetString("IndexCat1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se torne um profssional capacitado a trabalha com Back-End!.
        /// </summary>
        public static string IndexCat2 {
            get {
                return ResourceManager.GetString("IndexCat2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inglês.
        /// </summary>
        public static string Ingles {
            get {
                return ResourceManager.GetString("Ingles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Início.
        /// </summary>
        public static string Inicio {
            get {
                return ResourceManager.GetString("Inicio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Linguagem.
        /// </summary>
        public static string Linguagem {
            get {
                return ResourceManager.GetString("Linguagem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lista de cursos.
        /// </summary>
        public static string ListaCat1 {
            get {
                return ResourceManager.GetString("ListaCat1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lista de Usuários.
        /// </summary>
        public static string ListaUsuarios {
            get {
                return ResourceManager.GetString("ListaUsuarios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Material disponibilizado em PDF;.
        /// </summary>
        public static string MaterialPDF {
            get {
                return ResourceManager.GetString("MaterialPDF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nossa Plataforma.
        /// </summary>
        public static string NossaPlataforma {
            get {
                return ResourceManager.GetString("NossaPlataforma", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Com uma metologia moderna, a equipe desenvolveu A Devkey com o intuito de atender o máximo de pessoas possível, através de cursos online.
        ///                                    Contando com algumas tecnológias para melhor aproveitamento da plataforma..
        /// </summary>
        public static string NossaPlataformaTexto {
            get {
                return ResourceManager.GetString("NossaPlataformaTexto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O que nossos alunos dizem.
        /// </summary>
        public static string OQueDizem {
            get {
                return ResourceManager.GetString("OQueDizem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Perfil.
        /// </summary>
        public static string Perfil {
            get {
                return ResourceManager.GetString("Perfil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Perfil do usuário para melhor monitoramento de aulas;.
        /// </summary>
        public static string PerfilUsuario {
            get {
                return ResourceManager.GetString("PerfilUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A DevKey surgiu da necessidade de uma plataforma de ensino com qualidade e com preço acessível para todos, nosso objetivo é formar cada vez mais
        ///                        desenvolvedores aptos a entrarem no mercado de trabalho após finalizarem nossos cursos, já que a DevKey vem ganhando cada vez mais espaço dentro do mercado profissional..
        /// </summary>
        public static string Plataforma {
            get {
                return ResourceManager.GetString("Plataforma", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Português.
        /// </summary>
        public static string Portugues {
            get {
                return ResourceManager.GetString("Portugues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Principais.
        /// </summary>
        public static string Principais {
            get {
                return ResourceManager.GetString("Principais", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to As vídeos aulas podem ser acessadas facilmente de qualquer dispositivo, a qualquer hora..
        /// </summary>
        public static string ReponsivoTexto {
            get {
                return ResourceManager.GetString("ReponsivoTexto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Responsivo.
        /// </summary>
        public static string Responsivo {
            get {
                return ResourceManager.GetString("Responsivo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saber mais....
        /// </summary>
        public static string SaberMais {
            get {
                return ResourceManager.GetString("SaberMais", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sair.
        /// </summary>
        public static string Sair {
            get {
                return ResourceManager.GetString("Sair", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A nossa plataforma sempre procura inovar o mercado de ensino, com esse intuito dentre os nossos serviços encontra-se pontos importantíssimos para melhor aproveitamento de nossos alunos..
        /// </summary>
        public static string Servicos {
            get {
                return ResourceManager.GetString("Servicos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nossos.
        /// </summary>
        public static string ServicosTitle1 {
            get {
                return ResourceManager.GetString("ServicosTitle1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Serviços.
        /// </summary>
        public static string ServicosTitle2 {
            get {
                return ResourceManager.GetString("ServicosTitle2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sobre.
        /// </summary>
        public static string Sobre {
            get {
                return ResourceManager.GetString("Sobre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O nosso suporte, conta com um chat na qual o aluno ou novo usuário pode tirar suas dúvidas sem qualquer restrição..
        /// </summary>
        public static string SuporteTexto {
            get {
                return ResourceManager.GetString("SuporteTexto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suporte.
        /// </summary>
        public static string SuporteTitle {
            get {
                return ResourceManager.GetString("SuporteTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vídeos.
        /// </summary>
        public static string VideosTitle {
            get {
                return ResourceManager.GetString("VideosTitle", resourceCulture);
            }
        }
    }
}
